<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class permissions extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->truncate();
        $permissions=[
            [
                'module' => 'Factory',
                'sub_module' =>'Factory Add',
                'display_name' =>'Add Factory',
                'status' => '1',
                'order_sequence' =>'4',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Factory',
                'sub_module' =>'Factory Edit',
                'display_name' =>'Edit Factory',
                'status' => '0',
                'order_sequence' =>'5',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'PCU',
                'sub_module' =>'PCU Add',
                'display_name' =>'Add PCU',
                'status' => '1',
                'order_sequence' =>'6',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'PCU',
                'sub_module' =>'PCU Edit',
                'display_name' =>'Edit PCU',
                'status' => '0',
                'order_sequence' =>'7',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Fabric',
                'sub_module' =>'Fabric Add',
                'display_name' =>'Add Fabric',
                'status' => '1',
                'order_sequence' =>'10',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Article',
                'sub_module' =>'Article Add',
                'display_name' =>'Add Article',
                'status' => '1',
                'order_sequence' =>'12',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Category',
                'sub_module' =>'Category Add',
                'display_name' =>'Add Category',
                'status' => '1',
                'order_sequence' =>'11',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Color',
                'sub_module' =>'Color Add',
                'display_name' =>'Add Color',
                'status' => '1',
                'order_sequence' =>'13',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Color',
                'sub_module' =>'Color Edit',
                'display_name' =>'Edit Color',
                'status' => '0',
                'order_sequence' =>'14',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Size',
                'sub_module' =>'Size Add',
                'display_name' =>'Add Size',
                'status' => '1',
                'order_sequence' =>'15',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Size',
                'sub_module' =>'Size Edit',
                'display_name' =>'Edit Size',
                'status' => '0',
                'order_sequence' =>'16',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Contacts',
                'sub_module' =>'Contacts Add',
                'display_name' =>'Add Contacts',
                'status' => '0',
                'order_sequence' =>'17',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Staffs',
                'sub_module' =>'View Staff',
                'display_name' =>'View Staff',
                'status' => '1',
                'order_sequence' =>'32',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Staffs',
                'sub_module' =>'Staff Add',
                'display_name' =>'Add Staff',
                'status' => '1',
                'order_sequence' =>'33',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Staffs',
                'sub_module' =>'Staff Edit',
                'display_name' =>'Edit Staff',
                'status' => '1',
                'order_sequence' =>'34',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Task',
                'sub_module' =>'Task Edit Template',
                'display_name' =>'Edit Task Template',
                'status' => '1',
                'order_sequence' =>'18',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Task',
                'sub_module' =>'Task File Upload',
                'display_name' =>'Task File Upload',
                'status' => '1',
                'order_sequence' =>'19',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Order',
                'sub_module' =>'Add Order',
                'display_name' =>'Add Order',
                'status' => '1',
                'order_sequence' =>'1',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Order',
                'sub_module' =>'View All Orders',
                'display_name' =>'View All Orders',
                'status' => '1',
                'order_sequence' =>'2',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Order',
                'sub_module' =>'Edit Order',
                'display_name' =>'Edit Order',
                'status' => '1',
                'order_sequence' =>'3',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Roles',
                'sub_module' =>'Add Roles',
                'display_name' =>'Add Roles',
                'status' => '0',
                'order_sequence' =>'29',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Roles',
                'sub_module' =>'View Permissions',
                'display_name' =>'View Permissions',
                'status' => '1',
                'order_sequence' =>'30',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Roles',
                'sub_module' =>'Add Permissions',
                'display_name' =>'Add Permissions',
                'status' => '1',
                'order_sequence' =>'31',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Task Update',
                'sub_module' =>'View Task Updates',
                'display_name' =>'View Task Update',
                'status' => '1',
                'order_sequence' =>'21',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Task Update',
                'sub_module' =>'Add Task Updates',
                'display_name' =>'Add Task Update',
                'status' => '1',
                'order_sequence' =>'22',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Data Input',
                'sub_module' =>'View Data Input',
                'display_name' =>'View Data Input',
                'status' => '1',
                'order_sequence' =>'26',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Data Input',
                'sub_module' =>'Add Data Input',
                'display_name' =>'Add Data Input',
                'status' => '1',
                'order_sequence' =>'27',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Pending Task',
                'sub_module' =>'View Pending Task',
                'display_name' =>'View Pending Task',
                'status' => '1',
                'order_sequence' =>'24',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Pending Task',
                'sub_module' =>'Download Pending Task Report',
                'display_name' =>'Download Pending Task Report',
                'status' => '1',
                'order_sequence' =>'25',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Calendar Configuration',
                'sub_module' =>'View Calendar Configuration',
                'display_name' =>'View Calendar Configuration',
                'status' => '1',
                'order_sequence' =>'35',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Calendar Configuration',
                'sub_module' =>'Add/Edit Calendar Configuration',
                'display_name' =>'Add/Edit Calendar Configuration',
                'status' => '1',
                'order_sequence' =>'36',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Buyer',
                'sub_module' =>'Buyer Add',
                'display_name' =>'Add Buyer',
                'status' => '1',
                'order_sequence' =>'8',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Buyer',
                'sub_module' =>'Buyer Edit',
                'display_name' =>'Edit Buyer',
                'status' => '0',
                'order_sequence' =>'9',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Task',
                'sub_module' =>'Task File Delete',
                'display_name' =>'Delete Task File',
                'status' => '1',
                'order_sequence' =>'20',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Data Input',
                'sub_module' =>'Edit Data Input',
                'display_name' =>'Edit Data Input',
                'status' => '1',
                'order_sequence' =>'28',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Task Update',
                'sub_module' =>"Edit Others Task",
                'display_name' =>"Edit Other's Task",
                'status' => '1',
                'order_sequence' =>'23',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Order',
                'sub_module' =>'Add Price',
                'display_name' =>'Add Price',
                'status' => '1',
                'order_sequence' =>'3',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Order',
                'sub_module' =>'View Price',
                'display_name' =>'View Price',
                'status' => '1',
                'order_sequence' =>'3',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Order',
                'sub_module' =>'Edit Price',
                'display_name' =>'Edit Price',
                'status' => '1',
                'order_sequence' =>'3',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Order Status',
                'sub_module' =>'View Order Status',
                'display_name' =>'View Order Status',
                'status' => '1',
                'order_sequence' =>'37',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Order Status',
                'sub_module' =>'Complete Order',
                'display_name' =>'Complete Order',
                'status' => '1',
                'order_sequence' =>'38',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Order Status',
                'sub_module' =>'Cancel Order',
                'display_name' =>'Cancel Order',
                'status' => '1',
                'order_sequence' =>'39',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Order Status',
                'sub_module' =>'Delete Order',
                'display_name' =>'Delete Order',
                'status' => '1',
                'order_sequence' =>'40',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Reports',
                'sub_module' =>'View Report',
                'display_name' =>'View Report',
                'status' => '1',
                'order_sequence' =>'41',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            [
                'module' => 'Reports',
                'sub_module' =>'Download Report',
                'display_name' =>'Download Report',
                'status' => '1',
                'order_sequence' =>'42',
                'created_at' =>date("Y-m-d H:i:s"),
                'updated_at' =>date("Y-m-d H:i:s"),
            ],
            
            ];
            DB::table('permissions')->insert($permissions);
    }
}
