<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlanDetails extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('plan_price_details')->truncate();
        $planPriceDetails = [
            [
                'plan_name' => 'Trial',
                'type' => 'Monthly',
                'no_of_month'=>'1',
                'no_of_days'=>'28',
                'price' => '0.00',
                'yearly_price' => '0.00',
                'special_price' => '0.00',
                'currency' => 'USD',
                'no_of_group' => '1',
                'no_of_user' => '2',
                'no_of_style' => '1',
                'no_of_workspace' => '1',
                'max_storage_size' => '10',
                'report_range' => '30',
                'download_report' => '9',
                'notify_email_upcoming_task'=>'9',
                'notify_email_delayed_task'=>'9',
                'notify_whatsapp_upcoming_task'=>'9',
                'notify_whatsapp_delayed_task'=>'9',
                'notify_linemessenger_upcoming_task'=>'9',
                'notify_linemessenger_delayed_task'=>'9',
                'status'=>'1',
                'created_at'=>date("Y-m-d H:i:s"),
                'updated_at'=>date("Y-m-d H:i:s")
            ],
            [
                'plan_name' => 'Silver',
                'type' => 'Monthly',
                'no_of_month'=>'1',
                'no_of_days'=>'30',
                'price' => '29.99',
                'yearly_price' => '0',
                'special_price' => '0.00',
                'currency' => 'USD',
                'no_of_group' => '3',
                'no_of_user' => '10',
                'no_of_style' => '5',
                'no_of_workspace' => '1',
                'max_storage_size' => '50',
                'report_range' => '90',
                'download_report' => '8',
                'notify_email_upcoming_task'=>'8',
                'notify_email_delayed_task'=>'9',
                'notify_whatsapp_upcoming_task'=>'9',
                'notify_whatsapp_delayed_task'=>'9',
                'notify_linemessenger_upcoming_task'=>'9',
                'notify_linemessenger_delayed_task'=>'9',
                'status'=>'1',
                'created_at'=>date("Y-m-d H:i:s"),
                'updated_at'=>date("Y-m-d H:i:s")
            ],
            [
                'plan_name' => 'Gold',
                'type' => 'Monthly',
                'no_of_month'=>'1',
                'no_of_days'=>'30',
                'price' => '39.99',
                'yearly_price' => '0',
                'special_price' => '0.00',
                'currency' => 'USD',
                'no_of_group' => '5',
                'no_of_user' => '15',
                'no_of_style' => '10',
                'no_of_workspace' => '1',
                'max_storage_size' => '100',
                'report_range' => '120',
                'download_report' => '8',
                'notify_email_upcoming_task'=>'8',
                'notify_email_delayed_task'=>'8',
                'notify_whatsapp_upcoming_task'=>'8',
                'notify_whatsapp_delayed_task'=>'8',
                'notify_linemessenger_upcoming_task'=>'9',
                'notify_linemessenger_delayed_task'=>'9',
                'status'=>'1',
                'created_at'=>date("Y-m-d H:i:s"),
                'updated_at'=>date("Y-m-d H:i:s")
            ],
            [
                'plan_name' => 'Platinum',
                'type' => 'Monthly',
                'no_of_month'=>'1',
                'no_of_days'=>'30',
                'price' => '49.99',
                'yearly_price' => '0',
                'special_price' => '0.00',
                'currency' => 'USD',
                'no_of_group' => '10',
                'no_of_user' => '25',
                'no_of_style' => '25',
                'no_of_workspace' => '1',
                'max_storage_size' => '1000',
                'report_range' => '180',
                'download_report' => '8',
                'notify_email_upcoming_task'=>'8',
                'notify_email_delayed_task'=>'8',
                'notify_whatsapp_upcoming_task'=>'8',
                'notify_whatsapp_delayed_task'=>'8',
                'notify_linemessenger_upcoming_task'=>'9',
                'notify_linemessenger_delayed_task'=>'9',
                'status'=>'1',
                'created_at'=>date("Y-m-d H:i:s"),
                'updated_at'=>date("Y-m-d H:i:s")
            ],
            [
                'plan_name' => 'Silver',
                'type' => 'Yearly',
                'no_of_month'=>'12',
                'no_of_days'=>'360',
                'price' => '345.99',
                'yearly_price' => '0',
                'special_price' => '0.00',
                'currency' => 'USD',
                'no_of_group' => '3',
                'no_of_user' => '10',
                'no_of_style' => '5',
                'no_of_workspace' => '1',
                'max_storage_size' => '50',
                'report_range' => '90',
                'download_report' => '8',
                'notify_email_upcoming_task'=>'8',
                'notify_email_delayed_task'=>'9',
                'notify_whatsapp_upcoming_task'=>'9',
                'notify_whatsapp_delayed_task'=>'9',
                'notify_linemessenger_upcoming_task'=>'9',
                'notify_linemessenger_delayed_task'=>'9',
                'status'=>'1',
                'created_at'=>date("Y-m-d H:i:s"),
                'updated_at'=>date("Y-m-d H:i:s")
            ],
            [
                'plan_name' => 'Gold',
                'type' => 'Yearly',
                'no_of_month'=>'12',
                'no_of_days'=>'360',
                'price' => '460.00',
                'yearly_price' => '0',
                'special_price' => '0.00',
                'currency' => 'USD',
                'no_of_group' => '5',
                'no_of_user' => '15',
                'no_of_style' => '10',
                'no_of_workspace' => '1',
                'max_storage_size' => '100',
                'report_range' => '120',
                'download_report' => '8',
                'notify_email_upcoming_task'=>'8',
                'notify_email_delayed_task'=>'8',
                'notify_whatsapp_upcoming_task'=>'8',
                'notify_whatsapp_delayed_task'=>'8',
                'notify_linemessenger_upcoming_task'=>'9',
                'notify_linemessenger_delayed_task'=>'9',
                'status'=>'1',
                'created_at'=>date("Y-m-d H:i:s"),
                'updated_at'=>date("Y-m-d H:i:s")
            ],
            [
                'plan_name' => 'Platinum',
                'type' => 'Yearly',
                'no_of_month'=>'12',
                'no_of_days'=>'360',
                'price' => '570.00',
                'yearly_price' => '0',
                'special_price' => '0.00',
                'currency' => 'USD',
                'no_of_group' => '10',
                'no_of_user' => '25',
                'no_of_style' => '25',
                'no_of_workspace' => '1',
                'max_storage_size' => '1000',
                'report_range' => '180',
                'download_report' => '8',
                'notify_email_upcoming_task'=>'8',
                'notify_email_delayed_task'=>'8',
                'notify_whatsapp_upcoming_task'=>'8',
                'notify_whatsapp_delayed_task'=>'8',
                'notify_linemessenger_upcoming_task'=>'9',
                'notify_linemessenger_delayed_task'=>'9',
                'status'=>'1',
                'created_at'=>date("Y-m-d H:i:s"),
                'updated_at'=>date("Y-m-d H:i:s")
            ],
            [
                'plan_name' => 'Ultimate',
                'type' => 'Yearly',
                'no_of_month'=>'12',
                'no_of_days'=>'365',
                'price' => '750.00',
                'yearly_price' => '0',
                'special_price' => '0.00',
                'currency' => 'USD',
                'no_of_group' => '20',
                'no_of_user' => '50',
                'no_of_style' => '40',
                'no_of_workspace' => '1',
                'max_storage_size' => '1500',
                'report_range' => '240',
                'download_report' => '8',
                'notify_email_upcoming_task'=>'8',
                'notify_email_delayed_task'=>'8',
                'notify_whatsapp_upcoming_task'=>'8',
                'notify_whatsapp_delayed_task'=>'8',
                'notify_linemessenger_upcoming_task'=>'9',
                'notify_linemessenger_delayed_task'=>'9',
                'status'=>'1',
                'created_at'=>date("Y-m-d H:i:s"),
                'updated_at'=>date("Y-m-d H:i:s")
            ],
        ];
        DB::table('plan_price_details')->insert($planPriceDetails);
    }
}
